blog/api/urls.py
from django.conf.urls import url
from django.contrib import admin
#from django.contrib import admin

from django.urls import path
from .view import (
        PostCreateAPIView,
        PostDeleteAPIView,
        PostDetailAPIView,
        PostListAPIView,
        PostUpdateAPIView
        )

app_name = 'blog'

urlpatterns=[
    path('',PostListAPIView.as_view(),name='post_list'),
    #id
    url(r'^create/$',PostCreateAPIView.as_view(), name = 'create'),
    url(r'^(?P<pk>\d+)/$',PostDetailAPIView.as_view(), name = 'detail'),
    url(r'^(?P<pk>\d+)/edit/$',PostUpdateAPIView.as_view(), name = 'update'),
    url(r'^(?P<pk>\d+)/delete/$',PostDeleteAPIView.as_view(), name = 'delete'),

    #slug
    # url(r'^(?P<slug>[\w-]+)/$',PostDetailAPIView.as_view(), name = 'detail'),
    # url(r'^(?P<slug>[\w-]+)/edit/$',PostUpdateAPIView.as_view(), name = 'update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$',PostDeleteAPIView.as_view(), name = 'delete'),

   # Url(r'^S',PostListAPIView.as_view(), name = 'list'),
    # path('',views.post_list,name='post_list'),
   # path('',views.PostListView.as_view(), name='post_list'),
   #  path('tag/<slug:tag_slug>',views.post_list,name='post_list_by_tag'),
   #  path('<int:year>/<int:month>/<int:day>/<slug:post>/',
   #       views.post_detail,
   #       name='post_detail'),
   #  path('<int:post_id>/share/',
   #       views.post_share, name='post_share'),
]



#{post.title.substr(0, 3)}...
#{post.excerpt.substr(0, 3)}...

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns=[
    path('',views.post_list,name='post_list'),
    #path('',views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
]

gavindublog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls' , namespace = 'blog')),
    path('api/blog/', include('blog.api.urls' , namespace = 'blog-api')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
#from django.utils.text import slugify   #newly added in testing
from django.template.defaultfilters import slugify

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (('daft','Draft'),('published','Published'),
                      )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects = models.Manager() #default manager
    published =PublishedManager()#custom manager
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
            args= [self.publish.year,
                   self.publish.month,
                   self.publish.day,
                   self.slug])

    class Meta:
        ordering = ('-publish',)


    def _str__(self):
        return self.title


    # add this one to testing --  it checks whether the post about to be saved has a slug value, and if not, calls slugify to create a slug value for it.
    #test to ensure that slugs are actually created when saving a post.
    def save(self, *args, **kwargs):    #kwargs - allows to pass the variable length of keyword argumnet to function
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default =True)

    class Meta:
        ordering =('created',)

    def __str__(self):
        return f'comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Create your views here.

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 6 #to show posts
    template_name ='blog/post/list.html'

def post_list(request,tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag]) #given tag includes many to many relations


    paginator = Paginator(object_list,6) #6 posts in the single page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page':page,'posts':posts,'tag':tag}) #pushing the query set


#To display a single post

def post_detail(request, year, month, day, post):
    post= get_object_or_404(Post, slug=post, status='published',
                            publish__year = year, publish__month = month,
                            publish__day = day)

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id',flat = True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,'blog/post/detail.html',
                  {'post':post,
                   'comments':comments,
                   'new_comment':new_comment,
                   'comment_form':comment_form,
                   'similar_posts':similar_posts})



#sharing post via email

def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status='published')
    sent = False  #to share post

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            #......send email......
            post_url = request.build_absolute_uri(post.get_absolute_url()) #to complete url to the post
            subject = f"{cd['name']} recommends you read" f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject,message,'gavinduhgs95@gmail.com', [cd['to']])  #receiver
            sent = True

    else:
        form =EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,
                                                    'form':form,
                                                      'sent':sent})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel = "stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2> MY FIRST BLOG </h2>
        <p>

            I am Gavindu Sajeendra from Srilanka.
            I am an Undergraduate Student at Bauman Moscow State Technical University.
            This is my first Blog.I am creating this Blog site as My 3rd year Data base course Work.
        </p>
        <p>
            Here i am trying to give knowlegde about different fields.They are technology, education, Health, Motivation, Tourism, Entrepreneurship and Sports.
            this is knowlege power house to improve your knowledge of various fields from one place. I hope that you guys giving me a motivation ,putting comments.Futher you can also share my posts via emails to see others

        </p>

        <p> I have written {% total_posts %} posts so far  </p>
        <h3> Latest Posts </h3>
        {% show_latest_posts 3  %}

        <h3> Most Commented Posts </h3>
        {% get_most_commented_posts as  most_commented_posts %}
        <ul>
              {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html

{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
<h1> {{ post.title }} </h1>

<p class="date">
        published {{ post.publish }} by {{ post.author }}

    </p>

{{ post.body|linebreaks }}
<p>
    <a href = "{% url "blog:post_share" post.id %} ">
   Share this post</a>

</p>

<h2>Similar Posts</h2>
{% for post in similar_posts %}
<p>
    <a href ="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no Similar Posts yet.
{% endfor %}

{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment {{ total_comments|pluralize }}
</h2>
{% endwith %}

{% for comment in comments %}
<div class = "comment">
    <p class = "info">
        Comment {{ forloop.counter }} by {{ comment.name}} {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p> There are no comments yet.</p>
{% endfor %}

{% if new_comment %}
<h2> Your comment has been added</h2>
{% else %}
<h2>Add a new Comment</h2>
<form method ="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add Comment"></p>
</form>

{% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href = "{{ post.get_absolute_url }}">{{ post.title }}</a>

    </li>
    {% endfor %}

</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %} MY FIRST BLOG {% endblock %}

{% block content %}
  <h1> Knowledge Dock </h1>
{% if tag %}
<h2>Posts tagged with "{{tag.name}}"</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title}}
    </a>
</h2>
<p class="date">
    Published {{post.publish}} by {{ post.author}}
</p>
<p class"tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>

{{ post.body| truncatewords:30|linebreaks  }}
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a Post {% endblock %}
{% block content %}

{% if sent %}
    <h1>E-mail sent successfully </h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
</p>
{% else %}
    <h1>Share "{{ post.title}}" by e-mail</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type = "submit" value="Send E-Mail">
    </form>
{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>